version: "3.8"
services:
  api-service:
    build: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 5555:5555
    environment:
      PORT: 5555
      FLASK_DEBUG: 1

  test-service:
    build:
      context: .
      args:
        ENV: test
    volumes:
      - .:/usr/src/app/
    command: coverage run -m pytest tests/test_app.py && coverage report
